// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pb_rule.proto

package rule_engine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleType      string                 `protobuf:"bytes,1,opt,name=ruleType,proto3" json:"ruleType,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	RulePolicy    string                 `protobuf:"bytes,3,opt,name=rulePolicy,proto3" json:"rulePolicy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbRule) Reset() {
	*x = PbRule{}
	mi := &file_pb_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbRule) ProtoMessage() {}

func (x *PbRule) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbRule.ProtoReflect.Descriptor instead.
func (*PbRule) Descriptor() ([]byte, []int) {
	return file_pb_rule_proto_rawDescGZIP(), []int{0}
}

func (x *PbRule) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *PbRule) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *PbRule) GetRulePolicy() string {
	if x != nil {
		return x.RulePolicy
	}
	return ""
}

type PbBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          []*PbRule              `protobuf:"bytes,1,rep,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbBook) Reset() {
	*x = PbBook{}
	mi := &file_pb_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbBook) ProtoMessage() {}

func (x *PbBook) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbBook.ProtoReflect.Descriptor instead.
func (*PbBook) Descriptor() ([]byte, []int) {
	return file_pb_rule_proto_rawDescGZIP(), []int{1}
}

func (x *PbBook) GetRule() []*PbRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

var File_pb_rule_proto protoreflect.FileDescriptor

const file_pb_rule_proto_rawDesc = "" +
	"\n" +
	"\rpb_rule.proto\x12\vrule_engine\"^\n" +
	"\x06PbRule\x12\x1a\n" +
	"\bruleType\x18\x01 \x01(\tR\bruleType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x1e\n" +
	"\n" +
	"rulePolicy\x18\x03 \x01(\tR\n" +
	"rulePolicy\"1\n" +
	"\x06PbBook\x12'\n" +
	"\x04rule\x18\x01 \x03(\v2\x13.rule_engine.PbRuleR\x04ruleBFZDgithub.com/igoogolx/itun2socks/pkg/rule_engineb\x06proto3"

var (
	file_pb_rule_proto_rawDescOnce sync.Once
	file_pb_rule_proto_rawDescData []byte
)

func file_pb_rule_proto_rawDescGZIP() []byte {
	file_pb_rule_proto_rawDescOnce.Do(func() {
		file_pb_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_rule_proto_rawDesc), len(file_pb_rule_proto_rawDesc)))
	})
	return file_pb_rule_proto_rawDescData
}

var file_pb_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_rule_proto_goTypes = []any{
	(*PbRule)(nil), // 0: rule_engine.PbRule
	(*PbBook)(nil), // 1: rule_engine.PbBook
}
var file_pb_rule_proto_depIdxs = []int32{
	0, // 0: rule_engine.PbBook.rule:type_name -> rule_engine.PbRule
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_rule_proto_init() }
func file_pb_rule_proto_init() {
	if File_pb_rule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_rule_proto_rawDesc), len(file_pb_rule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_rule_proto_goTypes,
		DependencyIndexes: file_pb_rule_proto_depIdxs,
		MessageInfos:      file_pb_rule_proto_msgTypes,
	}.Build()
	File_pb_rule_proto = out.File
	file_pb_rule_proto_goTypes = nil
	file_pb_rule_proto_depIdxs = nil
}
